DELETE http://localhost:3001/api/persons/6125e8cba30aba1a96fd237b

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "qqq",
    "number": "00000000"
}

###

PUT http://localhost:3001/api/persons/6126078f2112239b6be4f00a
content-type: application/json

{
    "name": "q",
    "number": "11"
}